In [1]:
# iso ="[ F10*F8*F7*F6*F4*F2, F9*F8*F3*F2, F9*F8*F6*F2*F1, F8*F6*F2, F10*F7*F6*F5*F2,   F10*F9*F7*F6, F8, F8*F6, F10*F8*F7*F6, F9*F7*F6 ]"
iso1 = "[ f1*f3, f1*f4*f5, f1*f2*f3*f4, f1*f2*f4*f5, f1*f2*f3*f4*f5, f8, f6*f7,   f8*f9, f6*f8*f10, f6 ]"
iso2 = "[ f2*f4, f1*f2*f3, f4, f3*f4, f1*f2*f3*f5, f6, f6*f8, f9, f6*f7, f10 ]"
# iso = "[ F1, F2, F3, F4, F5, F6, F7, F8, F9, F10 ] -> [ F10*F9*F7*F6*F4*F1, F9*F4, F6*F4*F2, F10*F9*F8*F5*F4, F9*F8*F7*F4*F3,   F10*F9*F7*F6, F8*F7, F8*F6, F10*F9*F7, F9*F7*F6 ]"

In [3]:
iso = iso.replace(' ', "")
iso = iso.replace('[', "")
iso = iso.replace(']', "")
iso = iso.replace('f', "")
print(iso)
# ls = iso.split("->")
ls = iso.split(',') 
ls = [x.split("*") for x in ls]  
# ls[1] = ls[1].split('*') 
print(ls)

NameError: name 'iso' is not defined

In [2]:
def convertListtoBin(str, size):
    ans = ['0'] * size
    for x in str:
        ans[int(x) - 1] = "1"
    
    return ''.join(ans)

In [3]:
convertListtoBin(['1', '3'], 10)

'1010000000'

In [4]:
ls = [convertListtoBin(x, 10) for x in ls]


NameError: name 'ls' is not defined

In [5]:
print(ls)


NameError: name 'ls' is not defined

In [6]:
mat = [[int(y) for y in x] for x in ls]
mat

NameError: name 'ls' is not defined

In [7]:
import numpy as np

mat_np = np.array(mat)
mat_np = mat_np.T

NameError: name 'mat' is not defined

In [8]:
print(mat_np)

NameError: name 'mat_np' is not defined

In [9]:
np.linalg.det(mat_np)

NameError: name 'mat_np' is not defined

In [4]:
import numpy as np

def getMatrix(iso):
    iso = iso.replace(' ', "")
    iso = iso.replace('[', "")
    iso = iso.replace(']', "")
    iso = iso.replace('f', "")

    ls = iso.split(',') 
    ls = [x.split("*") for x in ls]  

    ls = [convertListtoBin(x, 10) for x in ls]

    mat = [[int(y) for y in x] for x in ls]
    mat_np = np.array(mat)
    mat_np = mat_np.T

    return mat_np


In [5]:
getMatrix(iso1)

array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

In [6]:
mat2 = getMatrix(iso2)

In [7]:
mat1 = getMatrix(iso1)

In [8]:
iso3 = "[ f2, f1*f2, f3*f4, f3, f1*f2*f4*f5, f6*f10, f6*f7, f6*f8*f10, f6*f9*f10, f6 ]"
iso4 = "[ f1*f2*f4, f1*f5, f2*f3, f5, f4*f5, f6*f8, f7, f8*f9, f8, f10 ]"

In [9]:
mat3 = getMatrix(iso3) 
mat4 = getMatrix(iso4) 

In [20]:
print(mat1)

[[1 1 1 1 1 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 0 0]
 [1 0 1 0 1 0 0 0 0 0]
 [0 1 1 1 1 0 0 0 0 0]
 [0 1 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 1]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 1 1 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]]


In [11]:
mat3

array([[0, 1, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 1, 0]])

In [12]:
mat4

array([[1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [19]:
print(mat1[0:5,0:5])
print()
print(mat1[5:10,5:10])

[[1 1 1 1 1]
 [0 0 1 1 1]
 [1 0 1 0 1]
 [0 1 1 1 1]
 [0 1 0 1 1]]

[[0 1 0 1 1]
 [0 1 0 0 0]
 [1 0 1 1 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


In [13]:
((np.matmul(mat3, mat4) % 2) == mat1).all()

True

In [17]:
from numpy import linalg as LA

eigenvalues, eigenvectors = LA.eig(mat2)

In [18]:
eigenvalues

array([ 1.        +0.00000000e+00j,  1.61803399+0.00000000e+00j,
        1.61803399+0.00000000e+00j, -0.61803399+9.17439958e-09j,
       -0.61803399-9.17439958e-09j, -0.5       +8.66025404e-01j,
       -0.5       -8.66025404e-01j,  1.        +0.00000000e+00j,
        1.        +0.00000000e+00j,  1.        +0.00000000e+00j])

In [25]:
gapRep = "["
for row in mat2:
    gapRep += "\n ["
    for entry in row:
        if entry == 0: gapRep += "0 * Z(2), "
        elif entry == 1: gapRep += "Z(2), "
    
    gapRep += ']'

gapRep += "\n]"

In [26]:
print(gapRep)

[
 [0 * Z(2), Z(2), 0 * Z(2), 0 * Z(2), Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), ]
 [Z(2), Z(2), 0 * Z(2), 0 * Z(2), Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), ]
 [0 * Z(2), Z(2), 0 * Z(2), Z(2), Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), ]
 [Z(2), 0 * Z(2), Z(2), Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), ]
 [0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), ]
 [0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), Z(2), Z(2), 0 * Z(2), Z(2), 0 * Z(2), ]
 [0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), Z(2), 0 * Z(2), ]
 [0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), ]
 [0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), Z(2), 0 * Z(2), 0 * Z(2), ]
 [0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), Z(2), ]
]


In [12]:
def getGapRep(mat):
    gapRep = "["
    for row in mat:
        gapRep += "\n ["
        for entry in row:
            if entry == 0: gapRep += "0 * Z(2), "
            elif entry == 1: gapRep += "    Z(2), "
        
        gapRep += '],'

    gapRep += "\n]"

    return gapRep


In [13]:
print(getGapRep(mat1))

[
 [    Z(2),     Z(2),     Z(2),     Z(2),     Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), ],
 [0 * Z(2), 0 * Z(2),     Z(2),     Z(2),     Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), ],
 [    Z(2), 0 * Z(2),     Z(2), 0 * Z(2),     Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), ],
 [0 * Z(2),     Z(2),     Z(2),     Z(2),     Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), ],
 [0 * Z(2),     Z(2), 0 * Z(2),     Z(2),     Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), ],
 [0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2),     Z(2), 0 * Z(2),     Z(2),     Z(2), ],
 [0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2),     Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), ],
 [0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2),     Z(2), 0 * Z(2),     Z(2),     Z(2), 0 * Z(2), ],
 [0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2),     Z(2), 0 * Z(2), 0 * Z(2), ],
 [0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0

In [33]:
print(getGapRep(mat2))

[
 [0 * Z(2), Z(2), 0 * Z(2), 0 * Z(2), Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), ],
 [Z(2), Z(2), 0 * Z(2), 0 * Z(2), Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), ],
 [0 * Z(2), Z(2), 0 * Z(2), Z(2), Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), ],
 [Z(2), 0 * Z(2), Z(2), Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), ],
 [0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), ],
 [0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), Z(2), Z(2), 0 * Z(2), Z(2), 0 * Z(2), ],
 [0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), Z(2), 0 * Z(2), ],
 [0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), ],
 [0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), Z(2), 0 * Z(2), 0 * Z(2), ],
 [0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), Z(2), ],
]


In [36]:
eig1 = np.array([ 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]).T

In [39]:
np.dot(mat1, eig1) % 2

array([0, 0, 1, 1, 1, 0, 0, 0, 0, 0])

In [32]:
def getLaTeXRep(mat):
    latexRep = "\\begin{bmatrix}\n"
    for row in mat:
        latexRep += "\t"
        for entry in row:
            latexRep += str(entry) + " & "
        
        latexRep = latexRep[:-3]
        latexRep += ' \\\\ \n'

    latexRep += "\\end{bmatrix}"

    return latexRep


In [33]:
print(getLaTeXRep(mat1))

\begin{bmatrix}
	1 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 \\ 
	0 & 0 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 \\ 
	1 & 0 & 1 & 0 & 1 & 0 & 0 & 0 & 0 & 0 \\ 
	0 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 \\ 
	0 & 1 & 0 & 1 & 1 & 0 & 0 & 0 & 0 & 0 \\ 
	0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 1 & 1 \\ 
	0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 \\ 
	0 & 0 & 0 & 0 & 0 & 1 & 0 & 1 & 1 & 0 \\ 
	0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 \\ 
	0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 \\ 
\end{bmatrix}


In [34]:
print(getLaTeXRep(mat2))

\begin{bmatrix}
	0 & 1 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 \\ 
	1 & 1 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 \\ 
	0 & 1 & 0 & 1 & 1 & 0 & 0 & 0 & 0 & 0 \\ 
	1 & 0 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\ 
	0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 \\ 
	0 & 0 & 0 & 0 & 0 & 1 & 1 & 0 & 1 & 0 \\ 
	0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 \\ 
	0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 \\ 
	0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 \\ 
	0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 \\ 
\end{bmatrix}


In [36]:
np.linalg.det(mat2)

1.0